### ISSUE TITLE
small mistake in zh-CN/c-cpp-fundamental.md

### ISSUE THREAD

**Issue by LiZhenhuan1019** [FrankHB/pl-docs#3]
原文:
### 3.2 声明和定义
首先，预处理 *阶段(phase)* 的 *宏定义(macro definition)* 不属于本章讨论的“定义”的外延。

在 ISO C++ 中，**声明总是定义，反过来不成立**
似乎应为:**定义总是声明,反过来不成立**

**Comment by FrankHB** [comment]
Typo confirmed.
